name: Test Action

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  models: read

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test the action
        id: test
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-files: 1
          target-coverage: 50
          create-pr: false

      - name: Check outputs
        run: |
          echo "Files processed: ${{ steps.test.outputs.files_processed }}"
          echo "Tests generated: ${{ steps.test.outputs.tests_generated }}"
          echo "Coverage report: ${{ steps.test.outputs.coverage_report }}"
          echo "PR URL: ${{ steps.test.outputs.pr_url }}"
          echo "Branch name: ${{ steps.test.outputs.branch_name }}"

  validate-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-inference requests PyYAML

      - name: Validate Python scripts
        run: |
          python -m py_compile scripts/get_coverage_data.py
          python -m py_compile scripts/generate_tests.py
          python -m py_compile scripts/create_pr.py
          echo "All scripts compiled successfully"

      - name: Test script help
        run: |
          python scripts/get_coverage_data.py --help
          python scripts/generate_tests.py --help
          python scripts/create_pr.py --help
